using System;
using System.Collections.Generic;

namespace Pokemon
{
class AttackList
{
    public Dictionary<string,BaseAttack> attacks;
    public AttackList()
    {
        attacks = new Dictionary<string, BaseAttack>();
        //"Name", "Type", "Category", "Contest", "PP", "Power", "Accuracy", "Gen" 

attacks.Add("Pound", new BaseAttack("Pound", "Normal", "Physical", "Tough", "35", "40", "100", "I"));
attacks.Add("Karate Chop", new BaseAttack("Karate Chop", "Fighting", "Physical", "Tough", "25", "50", "100", "I"));
attacks.Add("Double Slap", new BaseAttack("Double Slap", "Normal", "Physical", "Cute", "10", "15", "85", "I"));
attacks.Add("Comet Punch", new BaseAttack("Comet Punch", "Normal", "Physical", "Tough", "15", "18", "85", "I"));
attacks.Add("Mega Punch", new BaseAttack("Mega Punch", "Normal", "Physical", "Tough", "20", "80", "85", "I"));
attacks.Add("Pay Day", new BaseAttack("Pay Day", "Normal", "Physical", "Clever", "20", "40", "100", "I"));
attacks.Add("Fire Punch", new BaseAttack("Fire Punch", "Fire", "Physical", "Tough", "15", "75", "100", "I"));
attacks.Add("Ice Punch", new BaseAttack("Ice Punch", "Ice", "Physical", "Beautiful", "15", "75", "100", "I"));
attacks.Add("Thunder Punch", new BaseAttack("Thunder Punch", "Electric", "Physical", "Cool", "15", "75", "100", "I"));
attacks.Add("Scratch", new BaseAttack("Scratch", "Normal", "Physical", "Tough", "35", "40", "100", "I"));
attacks.Add("Vice Grip", new BaseAttack("Vice Grip", "Normal", "Physical", "Tough", "30", "55", "100", "I"));
attacks.Add("Guillotine", new BaseAttack("Guillotine", "Normal", "Physical", "Cool", "5", "", "", "I"));
attacks.Add("Razor Wind", new BaseAttack("Razor Wind", "Normal", "Special", "Cool", "10", "80", "100", "I"));
attacks.Add("Swords Dance", new BaseAttack("Swords Dance", "Normal", "Status", "Beautiful", "20", "", "", "I"));
attacks.Add("Cut", new BaseAttack("Cut", "Normal", "Physical", "Cool", "30", "50", "95", "I"));
attacks.Add("Gust", new BaseAttack("Gust", "Flying", "Special", "Clever", "35", "40", "100", "I"));
attacks.Add("Wing Attack", new BaseAttack("Wing Attack", "Flying", "Physical", "Cool", "35", "60", "100", "I"));
attacks.Add("Whirlwind", new BaseAttack("Whirlwind", "Normal", "Status", "Clever", "20", "", "", "I"));
attacks.Add("Fly", new BaseAttack("Fly", "Flying", "Physical", "Clever", "15", "90", "95", "I"));
attacks.Add("Bind", new BaseAttack("Bind", "Normal", "Physical", "Tough", "20", "15", "85", "I"));
attacks.Add("Slam", new BaseAttack("Slam", "Normal", "Physical", "Tough", "20", "80", "75", "I"));
attacks.Add("Vine Whip", new BaseAttack("Vine Whip", "Grass", "Physical", "Cool", "25", "45", "100", "I"));
attacks.Add("Stomp", new BaseAttack("Stomp", "Normal", "Physical", "Tough", "20", "65", "100", "I"));
attacks.Add("Double Kick", new BaseAttack("Double Kick", "Fighting", "Physical", "Cool", "30", "30", "100", "I"));
attacks.Add("Mega Kick", new BaseAttack("Mega Kick", "Normal", "Physical", "Cool", "5", "120", "75", "I"));
attacks.Add("Jump Kick", new BaseAttack("Jump Kick", "Fighting", "Physical", "Cool", "10", "100", "95", "I"));
attacks.Add("Rolling Kick", new BaseAttack("Rolling Kick", "Fighting", "Physical", "Cool", "15", "60", "85", "I"));
attacks.Add("Sand Attack", new BaseAttack("Sand Attack", "Ground", "Status", "Cute", "15", "", "100", "I"));
attacks.Add("Headbutt", new BaseAttack("Headbutt", "Normal", "Physical", "Tough", "15", "70", "100", "I"));
attacks.Add("Horn Attack", new BaseAttack("Horn Attack", "Normal", "Physical", "Cool", "25", "65", "100", "I"));
attacks.Add("Fury Attack", new BaseAttack("Fury Attack", "Normal", "Physical", "Cool", "20", "15", "85", "I"));
attacks.Add("Horn Drill", new BaseAttack("Horn Drill", "Normal", "Physical", "Cool", "5", "", "", "I"));
attacks.Add("Tackle", new BaseAttack("Tackle", "Normal", "Physical", "Tough", "35", "40", "100", "I"));
attacks.Add("Body Slam", new BaseAttack("Body Slam", "Normal", "Physical", "Tough", "15", "85", "100", "I"));
attacks.Add("Wrap", new BaseAttack("Wrap", "Normal", "Physical", "Tough", "20", "15", "90", "I"));
attacks.Add("Take Down", new BaseAttack("Take Down", "Normal", "Physical", "Tough", "20", "90", "85", "I"));
attacks.Add("Thrash", new BaseAttack("Thrash", "Normal", "Physical", "Tough", "10", "120", "100", "I"));
attacks.Add("Double-Edge", new BaseAttack("Double-Edge", "Normal", "Physical", "Tough", "15", "120", "100", "I"));
attacks.Add("Tail Whip", new BaseAttack("Tail Whip", "Normal", "Status", "Cute", "30", "", "100", "I"));
attacks.Add("Poison Sting", new BaseAttack("Poison Sting", "Poison", "Physical", "Clever", "35", "15", "100", "I"));
attacks.Add("Twineedle", new BaseAttack("Twineedle", "Bug", "Physical", "Cool", "20", "25", "100", "I"));
attacks.Add("Pin Missile", new BaseAttack("Pin Missile", "Bug", "Physical", "Cool", "20", "25", "95", "I"));
attacks.Add("Leer", new BaseAttack("Leer", "Normal", "Status", "Cool", "30", "", "100", "I"));
attacks.Add("Bite", new BaseAttack("Bite", "Dark", "Physical", "Tough", "25", "60", "100", "I"));
attacks.Add("Growl", new BaseAttack("Growl", "Normal", "Status", "Cute", "40", "", "100", "I"));
attacks.Add("Roar", new BaseAttack("Roar", "Normal", "Status", "Cool", "20", "", "", "I"));
attacks.Add("Sing", new BaseAttack("Sing", "Normal", "Status", "Cute", "15", "", "55", "I"));
attacks.Add("Supersonic", new BaseAttack("Supersonic", "Normal", "Status", "Clever", "20", "", "55", "I"));
attacks.Add("Sonic Boom", new BaseAttack("Sonic Boom", "Normal", "Special", "Cool", "20", "", "90", "I"));
attacks.Add("Disable", new BaseAttack("Disable", "Normal", "Status", "Clever", "20", "", "100", "I"));
attacks.Add("Acid", new BaseAttack("Acid", "Poison", "Special", "Clever", "30", "40", "100", "I"));
attacks.Add("Ember", new BaseAttack("Ember", "Fire", "Special", "Cute", "25", "40", "100", "I"));
attacks.Add("Flamethrower", new BaseAttack("Flamethrower", "Fire", "Special", "Beautiful", "15", "90", "100", "I"));
attacks.Add("Mist", new BaseAttack("Mist", "Ice", "Status", "Beautiful", "30", "", "", "I"));
attacks.Add("Water Gun", new BaseAttack("Water Gun", "Water", "Special", "Cute", "25", "40", "100", "I"));
attacks.Add("Hydro Pump", new BaseAttack("Hydro Pump", "Water", "Special", "Beautiful", "5", "110", "80", "I"));
attacks.Add("Surf", new BaseAttack("Surf", "Water", "Special", "Beautiful", "15", "90", "100", "I"));
attacks.Add("Ice Beam", new BaseAttack("Ice Beam", "Ice", "Special", "Beautiful", "10", "90", "100", "I"));
attacks.Add("Blizzard", new BaseAttack("Blizzard", "Ice", "Special", "Beautiful", "5", "110", "70", "I"));
attacks.Add("Psybeam", new BaseAttack("Psybeam", "Psychic", "Special", "Beautiful", "20", "65", "100", "I"));
attacks.Add("Bubble Beam", new BaseAttack("Bubble Beam", "Water", "Special", "Beautiful", "20", "65", "100", "I"));
attacks.Add("Aurora Beam", new BaseAttack("Aurora Beam", "Ice", "Special", "Beautiful", "20", "65", "100", "I"));
attacks.Add("Hyper Beam", new BaseAttack("Hyper Beam", "Normal", "Special", "Cool", "5", "150", "90", "I"));
attacks.Add("Peck", new BaseAttack("Peck", "Flying", "Physical", "Cool", "35", "35", "100", "I"));
attacks.Add("Drill Peck", new BaseAttack("Drill Peck", "Flying", "Physical", "Cool", "20", "80", "100", "I"));
attacks.Add("Submission", new BaseAttack("Submission", "Fighting", "Physical", "Cool", "20", "80", "80", "I"));
attacks.Add("Low Kick", new BaseAttack("Low Kick", "Fighting", "Physical", "Tough", "20", "", "100", "I"));
attacks.Add("Counter", new BaseAttack("Counter", "Fighting", "Physical", "Tough", "20", "", "100", "I"));
attacks.Add("Seismic Toss", new BaseAttack("Seismic Toss", "Fighting", "Physical", "Tough", "20", "", "100", "I"));
attacks.Add("Strength", new BaseAttack("Strength", "Normal", "Physical", "Tough", "15", "80", "100", "I"));
attacks.Add("Absorb", new BaseAttack("Absorb", "Grass", "Special", "Clever", "25", "20", "100", "I"));
attacks.Add("Mega Drain", new BaseAttack("Mega Drain", "Grass", "Special", "Clever", "15", "40", "100", "I"));
attacks.Add("Leech Seed", new BaseAttack("Leech Seed", "Grass", "Status", "Clever", "10", "", "90", "I"));
attacks.Add("Growth", new BaseAttack("Growth", "Normal", "Status", "Beautiful", "20", "", "", "I"));
attacks.Add("Razor Leaf", new BaseAttack("Razor Leaf", "Grass", "Physical", "Cool", "25", "55", "95", "I"));
attacks.Add("Solar Beam", new BaseAttack("Solar Beam", "Grass", "Special", "Cool", "10", "120", "100", "I"));
attacks.Add("Poison Powder", new BaseAttack("Poison Powder", "Poison", "Status", "Clever", "35", "", "75", "I"));
attacks.Add("Stun Spore", new BaseAttack("Stun Spore", "Grass", "Status", "Clever", "30", "", "75", "I"));
attacks.Add("Sleep Powder", new BaseAttack("Sleep Powder", "Grass", "Status", "Clever", "15", "", "75", "I"));
attacks.Add("Petal Dance", new BaseAttack("Petal Dance", "Grass", "Special", "Beautiful", "10", "120", "100", "I"));
attacks.Add("String Shot", new BaseAttack("String Shot", "Bug", "Status", "Clever", "40", "", "95", "I"));
attacks.Add("Dragon Rage", new BaseAttack("Dragon Rage", "Dragon", "Special", "Cool", "10", "", "100", "I"));
attacks.Add("Fire Spin", new BaseAttack("Fire Spin", "Fire", "Special", "Beautiful", "15", "35", "85", "I"));
attacks.Add("Thunder Shock", new BaseAttack("Thunder Shock", "Electric", "Special", "Cool", "30", "40", "100", "I"));
attacks.Add("Thunderbolt", new BaseAttack("Thunderbolt", "Electric", "Special", "Cool", "15", "90", "100", "I"));
attacks.Add("Thunder Wave", new BaseAttack("Thunder Wave", "Electric", "Status", "Cool", "20", "", "90", "I"));
attacks.Add("Thunder", new BaseAttack("Thunder", "Electric", "Special", "Cool", "10", "110", "70", "I"));
attacks.Add("Rock Throw", new BaseAttack("Rock Throw", "Rock", "Physical", "Tough", "15", "50", "90", "I"));
attacks.Add("Earthquake", new BaseAttack("Earthquake", "Ground", "Physical", "Tough", "10", "100", "100", "I"));
attacks.Add("Fissure", new BaseAttack("Fissure", "Ground", "Physical", "Tough", "5", "", "", "I"));
attacks.Add("Dig", new BaseAttack("Dig", "Ground", "Physical", "Tough", "10", "80", "100", "I"));
attacks.Add("Toxic", new BaseAttack("Toxic", "Poison", "Status", "Clever", "10", "", "90", "I"));
attacks.Add("Confusion", new BaseAttack("Confusion", "Psychic", "Special", "Clever", "25", "50", "100", "I"));
attacks.Add("Psychic", new BaseAttack("Psychic", "Psychic", "Special", "Clever", "10", "90", "100", "I"));
attacks.Add("Hypnosis", new BaseAttack("Hypnosis", "Psychic", "Status", "Clever", "20", "", "60", "I"));
attacks.Add("Meditate", new BaseAttack("Meditate", "Psychic", "Status", "Beautiful", "40", "", "", "I"));
attacks.Add("Agility", new BaseAttack("Agility", "Psychic", "Status", "Cool", "30", "", "", "I"));
attacks.Add("Quick Attack", new BaseAttack("Quick Attack", "Normal", "Physical", "Cool", "30", "40", "100", "I"));
attacks.Add("Rage", new BaseAttack("Rage", "Normal", "Physical", "Tough", "20", "20", "100", "I"));
attacks.Add("Teleport", new BaseAttack("Teleport", "Psychic", "Status", "Cool", "20", "", "", "I"));
attacks.Add("Night Shade", new BaseAttack("Night Shade", "Ghost", "Special", "Clever", "15", "", "100", "I"));
attacks.Add("Mimic", new BaseAttack("Mimic", "Normal", "Status", "Cute", "10", "", "", "I"));
attacks.Add("Screech", new BaseAttack("Screech", "Normal", "Status", "Clever", "40", "", "85", "I"));
attacks.Add("Double Team", new BaseAttack("Double Team", "Normal", "Status", "Cool", "15", "", "", "I"));
attacks.Add("Recover", new BaseAttack("Recover", "Normal", "Status", "Clever", "10", "", "", "I"));
attacks.Add("Harden", new BaseAttack("Harden", "Normal", "Status", "Tough", "30", "", "", "I"));
attacks.Add("Minimize", new BaseAttack("Minimize", "Normal", "Status", "Cute", "10", "", "", "I"));
attacks.Add("Smokescreen", new BaseAttack("Smokescreen", "Normal", "Status", "Clever", "20", "", "100", "I"));
attacks.Add("Confuse Ray", new BaseAttack("Confuse Ray", "Ghost", "Status", "Clever", "10", "", "100", "I"));
attacks.Add("Withdraw", new BaseAttack("Withdraw", "Water", "Status", "Cute", "40", "", "", "I"));
attacks.Add("Defense Curl", new BaseAttack("Defense Curl", "Normal", "Status", "Cute", "40", "", "", "I"));
attacks.Add("Barrier", new BaseAttack("Barrier", "Psychic", "Status", "Cool", "20", "", "", "I"));
attacks.Add("Light Screen", new BaseAttack("Light Screen", "Psychic", "Status", "Beautiful", "30", "", "", "I"));
attacks.Add("Haze", new BaseAttack("Haze", "Ice", "Status", "Beautiful", "30", "", "", "I"));
attacks.Add("Reflect", new BaseAttack("Reflect", "Psychic", "Status", "Clever", "20", "", "", "I"));
attacks.Add("Focus Energy", new BaseAttack("Focus Energy", "Normal", "Status", "Cool", "30", "", "", "I"));
attacks.Add("Bide", new BaseAttack("Bide", "Normal", "Physical", "Tough", "10", "", "", "I"));
attacks.Add("Metronome", new BaseAttack("Metronome", "Normal", "Status", "Cute", "10", "", "", "I"));
attacks.Add("Mirror Move", new BaseAttack("Mirror Move", "Flying", "Status", "Clever", "20", "", "", "I"));
attacks.Add("Self-Destruct", new BaseAttack("Self-Destruct", "Normal", "Physical", "Beautiful", "5", "200", "100", "I"));
attacks.Add("Egg Bomb", new BaseAttack("Egg Bomb", "Normal", "Physical", "Cute", "10", "100", "75", "I"));
attacks.Add("Lick", new BaseAttack("Lick", "Ghost", "Physical", "Cute", "30", "30", "100", "I"));
attacks.Add("Smog", new BaseAttack("Smog", "Poison", "Special", "Tough", "20", "30", "70", "I"));
attacks.Add("Sludge", new BaseAttack("Sludge", "Poison", "Special", "Tough", "20", "65", "100", "I"));
attacks.Add("Bone Club", new BaseAttack("Bone Club", "Ground", "Physical", "Tough", "20", "65", "85", "I"));
attacks.Add("Fire Blast", new BaseAttack("Fire Blast", "Fire", "Special", "Beautiful", "5", "110", "85", "I"));
attacks.Add("Waterfall", new BaseAttack("Waterfall", "Water", "Physical", "Tough", "15", "80", "100", "I"));
attacks.Add("Clamp", new BaseAttack("Clamp", "Water", "Physical", "Tough", "15", "35", "85", "I"));
attacks.Add("Swift", new BaseAttack("Swift", "Normal", "Special", "Cool", "20", "60", "", "I"));
attacks.Add("Skull Bash", new BaseAttack("Skull Bash", "Normal", "Physical", "Tough", "10", "130", "100", "I"));
attacks.Add("Spike Cannon", new BaseAttack("Spike Cannon", "Normal", "Physical", "Cool", "15", "20", "100", "I"));
attacks.Add("Constrict", new BaseAttack("Constrict", "Normal", "Physical", "Tough", "35", "10", "100", "I"));
attacks.Add("Amnesia", new BaseAttack("Amnesia", "Psychic", "Status", "Cute", "20", "", "", "I"));
attacks.Add("Kinesis", new BaseAttack("Kinesis", "Psychic", "Status", "Clever", "15", "", "80", "I"));
attacks.Add("Soft-Boiled", new BaseAttack("Soft-Boiled", "Normal", "Status", "Cute", "10", "", "", "I"));
attacks.Add("High Jump Kick", new BaseAttack("High Jump Kick", "Fighting", "Physical", "Cool", "10", "130", "90", "I"));
attacks.Add("Glare", new BaseAttack("Glare", "Normal", "Status", "Tough", "30", "", "100", "I"));
attacks.Add("Dream Eater", new BaseAttack("Dream Eater", "Psychic", "Special", "Clever", "15", "100", "100", "I"));
attacks.Add("Poison Gas", new BaseAttack("Poison Gas", "Poison", "Status", "Clever", "40", "", "90", "I"));
attacks.Add("Barrage", new BaseAttack("Barrage", "Normal", "Physical", "Cute", "20", "15", "85", "I"));
attacks.Add("Leech Life", new BaseAttack("Leech Life", "Bug", "Physical", "Clever", "10", "80", "100", "I"));
attacks.Add("Lovely Kiss", new BaseAttack("Lovely Kiss", "Normal", "Status", "Beautiful", "10", "", "75", "I"));
attacks.Add("Sky Attack", new BaseAttack("Sky Attack", "Flying", "Physical", "Cool", "5", "140", "90", "I"));
attacks.Add("Transform", new BaseAttack("Transform", "Normal", "Status", "Clever", "10", "", "", "I"));
attacks.Add("Bubble", new BaseAttack("Bubble", "Water", "Special", "Cute", "30", "40", "100", "I"));
attacks.Add("Dizzy Punch", new BaseAttack("Dizzy Punch", "Normal", "Physical", "Cute", "10", "70", "100", "I"));
attacks.Add("Spore", new BaseAttack("Spore", "Grass", "Status", "Beautiful", "15", "", "100", "I"));
attacks.Add("Flash", new BaseAttack("Flash", "Normal", "Status", "Beautiful", "20", "", "100", "I"));
attacks.Add("Psywave", new BaseAttack("Psywave", "Psychic", "Special", "Clever", "15", "", "100", "I"));
attacks.Add("Splash", new BaseAttack("Splash", "Normal", "Status", "Cute", "40", "", "", "I"));
attacks.Add("Acid Armor", new BaseAttack("Acid Armor", "Poison", "Status", "Tough", "20", "", "", "I"));
attacks.Add("Crabhammer", new BaseAttack("Crabhammer", "Water", "Physical", "Tough", "10", "100", "90", "I"));
attacks.Add("Explosion", new BaseAttack("Explosion", "Normal", "Physical", "Beautiful", "5", "250", "100", "I"));
attacks.Add("Fury Swipes", new BaseAttack("Fury Swipes", "Normal", "Physical", "Tough", "15", "18", "80", "I"));
attacks.Add("Bonemerang", new BaseAttack("Bonemerang", "Ground", "Physical", "Tough", "10", "50", "90", "I"));
attacks.Add("Rest", new BaseAttack("Rest", "Psychic", "Status", "Cute", "10", "", "", "I"));
attacks.Add("Rock Slide", new BaseAttack("Rock Slide", "Rock", "Physical", "Tough", "10", "75", "90", "I"));
attacks.Add("Hyper Fang", new BaseAttack("Hyper Fang", "Normal", "Physical", "Cool", "15", "80", "90", "I"));
attacks.Add("Sharpen", new BaseAttack("Sharpen", "Normal", "Status", "Cute", "30", "", "", "I"));
attacks.Add("Conversion", new BaseAttack("Conversion", "Normal", "Status", "Beautiful", "30", "", "", "I"));
attacks.Add("Tri Attack", new BaseAttack("Tri Attack", "Normal", "Special", "Beautiful", "10", "80", "100", "I"));
attacks.Add("Super Fang", new BaseAttack("Super Fang", "Normal", "Physical", "Tough", "10", "", "90", "I"));
attacks.Add("Slash", new BaseAttack("Slash", "Normal", "Physical", "Cool", "20", "70", "100", "I"));
attacks.Add("Substitute", new BaseAttack("Substitute", "Normal", "Status", "Cute", "10", "", "", "I"));
attacks.Add("Struggle", new BaseAttack("Struggle", "Normal", "Physical", "Tough", "1", "50", "", "I"));
attacks.Add("Sketch", new BaseAttack("Sketch", "Normal", "Status", "Clever", "1", "", "", "II"));
attacks.Add("Triple Kick", new BaseAttack("Triple Kick", "Fighting", "Physical", "Cool", "10", "10", "90", "II"));
attacks.Add("Thief", new BaseAttack("Thief", "Dark", "Physical", "Tough", "25", "60", "100", "II"));
attacks.Add("Spider Web", new BaseAttack("Spider Web", "Bug", "Status", "Clever", "10", "", "", "II"));
attacks.Add("Mind Reader", new BaseAttack("Mind Reader", "Normal", "Status", "Clever", "5", "", "", "II"));
attacks.Add("Nightmare", new BaseAttack("Nightmare", "Ghost", "Status", "Clever", "15", "", "100", "II"));
attacks.Add("Flame Wheel", new BaseAttack("Flame Wheel", "Fire", "Physical", "Beautiful", "25", "60", "100", "II"));
attacks.Add("Snore", new BaseAttack("Snore", "Normal", "Special", "Cute", "15", "50", "100", "II"));
attacks.Add("Curse", new BaseAttack("Curse", "Ghost", "Status", "Tough", "10", "", "", "II"));
attacks.Add("Flail", new BaseAttack("Flail", "Normal", "Physical", "Cute", "15", "", "100", "II"));
attacks.Add("Conversion 2", new BaseAttack("Conversion 2", "Normal", "Status", "Beautiful", "30", "", "", "II"));
attacks.Add("Aeroblast", new BaseAttack("Aeroblast", "Flying", "Special", "Cool", "5", "100", "95", "II"));
attacks.Add("Cotton Spore", new BaseAttack("Cotton Spore", "Grass", "Status", "Beautiful", "40", "", "100", "II"));
attacks.Add("Reversal", new BaseAttack("Reversal", "Fighting", "Physical", "Cool", "15", "", "100", "II"));
attacks.Add("Spite", new BaseAttack("Spite", "Ghost", "Status", "Tough", "10", "", "100", "II"));
attacks.Add("Powder Snow", new BaseAttack("Powder Snow", "Ice", "Special", "Beautiful", "25", "40", "100", "II"));
attacks.Add("Protect", new BaseAttack("Protect", "Normal", "Status", "Cute", "10", "", "", "II"));
attacks.Add("Mach Punch", new BaseAttack("Mach Punch", "Fighting", "Physical", "Cool", "30", "40", "100", "II"));
attacks.Add("Scary Face", new BaseAttack("Scary Face", "Normal", "Status", "Tough", "10", "", "100", "II"));
attacks.Add("Feint Attack", new BaseAttack("Feint Attack", "Dark", "Physical", "Clever", "20", "60", "", "II"));
attacks.Add("Sweet Kiss", new BaseAttack("Sweet Kiss", "Fairy", "Status", "Cute", "10", "", "75", "II"));
attacks.Add("Belly Drum", new BaseAttack("Belly Drum", "Normal", "Status", "Cute", "10", "", "", "II"));
attacks.Add("Sludge Bomb", new BaseAttack("Sludge Bomb", "Poison", "Special", "Tough", "10", "90", "100", "II"));
attacks.Add("Mud-Slap", new BaseAttack("Mud-Slap", "Ground", "Special", "Cute", "10", "20", "100", "II"));
attacks.Add("Octazooka", new BaseAttack("Octazooka", "Water", "Special", "Tough", "10", "65", "85", "II"));
attacks.Add("Spikes", new BaseAttack("Spikes", "Ground", "Status", "Clever", "20", "", "", "II"));
attacks.Add("Zap Cannon", new BaseAttack("Zap Cannon", "Electric", "Special", "Cool", "5", "120", "50", "II"));
attacks.Add("Foresight", new BaseAttack("Foresight", "Normal", "Status", "Clever", "40", "", "", "II"));
attacks.Add("Destiny Bond", new BaseAttack("Destiny Bond", "Ghost", "Status", "Clever", "5", "", "", "II"));
attacks.Add("Perish Song", new BaseAttack("Perish Song", "Normal", "Status", "Beautiful", "5", "", "", "II"));
attacks.Add("Icy Wind", new BaseAttack("Icy Wind", "Ice", "Special", "Beautiful", "15", "55", "95", "II"));
attacks.Add("Detect", new BaseAttack("Detect", "Fighting", "Status", "Cool", "5", "", "", "II"));
attacks.Add("Bone Rush", new BaseAttack("Bone Rush", "Ground", "Physical", "Tough", "10", "25", "90", "II"));
attacks.Add("Lock-On", new BaseAttack("Lock-On", "Normal", "Status", "Clever", "5", "", "", "II"));
attacks.Add("Outrage", new BaseAttack("Outrage", "Dragon", "Physical", "Cool", "10", "120", "100", "II"));
attacks.Add("Sandstorm", new BaseAttack("Sandstorm", "Rock", "Status", "Tough", "10", "", "", "II"));
attacks.Add("Giga Drain", new BaseAttack("Giga Drain", "Grass", "Special", "Clever", "10", "75", "100", "II"));
attacks.Add("Endure", new BaseAttack("Endure", "Normal", "Status", "Tough", "10", "", "", "II"));
attacks.Add("Charm", new BaseAttack("Charm", "Fairy", "Status", "Cute", "20", "", "100", "II"));
attacks.Add("Rollout", new BaseAttack("Rollout", "Rock", "Physical", "Cute", "20", "30", "90", "II"));
attacks.Add("False Swipe", new BaseAttack("False Swipe", "Normal", "Physical", "Cool", "40", "40", "100", "II"));
attacks.Add("Swagger", new BaseAttack("Swagger", "Normal", "Status", "Cute", "15", "", "85", "II"));
attacks.Add("Milk Drink", new BaseAttack("Milk Drink", "Normal", "Status", "Cute", "10", "", "", "II"));
attacks.Add("Spark", new BaseAttack("Spark", "Electric", "Physical", "Cool", "20", "65", "100", "II"));
attacks.Add("Fury Cutter", new BaseAttack("Fury Cutter", "Bug", "Physical", "Cool", "20", "40", "95", "II"));
attacks.Add("Steel Wing", new BaseAttack("Steel Wing", "Steel", "Physical", "Cool", "25", "70", "90", "II"));
attacks.Add("Mean Look", new BaseAttack("Mean Look", "Normal", "Status", "Beautiful", "5", "", "", "II"));
attacks.Add("Attract", new BaseAttack("Attract", "Normal", "Status", "Cute", "15", "", "100", "II"));
attacks.Add("Sleep Talk", new BaseAttack("Sleep Talk", "Normal", "Status", "Cute", "10", "", "", "II"));
attacks.Add("Heal Bell", new BaseAttack("Heal Bell", "Normal", "Status", "Beautiful", "5", "", "", "II"));
attacks.Add("Return", new BaseAttack("Return", "Normal", "Physical", "Cute", "20", "", "100", "II"));
attacks.Add("Present", new BaseAttack("Present", "Normal", "Physical", "Cute", "15", "", "90", "II"));
attacks.Add("Frustration", new BaseAttack("Frustration", "Normal", "Physical", "Cute", "20", "", "100", "II"));
attacks.Add("Safeguard", new BaseAttack("Safeguard", "Normal", "Status", "Beautiful", "25", "", "", "II"));
attacks.Add("Pain Split", new BaseAttack("Pain Split", "Normal", "Status", "Clever", "20", "", "", "II"));
attacks.Add("Sacred Fire", new BaseAttack("Sacred Fire", "Fire", "Physical", "Beautiful", "5", "100", "95", "II"));
attacks.Add("Magnitude", new BaseAttack("Magnitude", "Ground", "Physical", "Tough", "30", "", "100", "II"));
attacks.Add("Dynamic Punch", new BaseAttack("Dynamic Punch", "Fighting", "Physical", "Cool", "5", "100", "50", "II"));
attacks.Add("Megahorn", new BaseAttack("Megahorn", "Bug", "Physical", "Cool", "10", "120", "85", "II"));
attacks.Add("Dragon Breath", new BaseAttack("Dragon Breath", "Dragon", "Special", "Cool", "20", "60", "100", "II"));
attacks.Add("Baton Pass", new BaseAttack("Baton Pass", "Normal", "Status", "Cute", "40", "", "", "II"));
attacks.Add("Encore", new BaseAttack("Encore", "Normal", "Status", "Cute", "5", "", "100", "II"));
attacks.Add("Pursuit", new BaseAttack("Pursuit", "Dark", "Physical", "Clever", "20", "40", "100", "II"));
attacks.Add("Rapid Spin", new BaseAttack("Rapid Spin", "Normal", "Physical", "Cool", "40", "20", "100", "II"));
attacks.Add("Sweet Scent", new BaseAttack("Sweet Scent", "Normal", "Status", "Cute", "20", "", "100", "II"));
attacks.Add("Iron Tail", new BaseAttack("Iron Tail", "Steel", "Physical", "Cool", "15", "100", "75", "II"));
attacks.Add("Metal Claw", new BaseAttack("Metal Claw", "Steel", "Physical", "Cool", "35", "50", "95", "II"));
attacks.Add("Vital Throw", new BaseAttack("Vital Throw", "Fighting", "Physical", "Cool", "10", "70", "", "II"));
attacks.Add("Morning Sun", new BaseAttack("Morning Sun", "Normal", "Status", "Beautiful", "5", "", "", "II"));
attacks.Add("Synthesis", new BaseAttack("Synthesis", "Grass", "Status", "Clever", "5", "", "", "II"));
attacks.Add("Moonlight", new BaseAttack("Moonlight", "Fairy", "Status", "Beautiful", "5", "", "", "II"));
attacks.Add("Hidden Power", new BaseAttack("Hidden Power", "Normal", "Special", "Clever", "15", "60", "100", "II"));
attacks.Add("Cross Chop", new BaseAttack("Cross Chop", "Fighting", "Physical", "Cool", "5", "100", "80", "II"));
attacks.Add("Twister", new BaseAttack("Twister", "Dragon", "Special", "Cool", "20", "40", "100", "II"));
attacks.Add("Rain Dance", new BaseAttack("Rain Dance", "Water", "Status", "Beautiful", "5", "", "", "II"));
attacks.Add("Sunny Day", new BaseAttack("Sunny Day", "Fire", "Status", "Beautiful", "5", "", "", "II"));
attacks.Add("Crunch", new BaseAttack("Crunch", "Dark", "Physical", "Tough", "15", "80", "100", "II"));
attacks.Add("Mirror Coat", new BaseAttack("Mirror Coat", "Psychic", "Special", "Beautiful", "20", "", "100", "II"));
attacks.Add("Psych Up", new BaseAttack("Psych Up", "Normal", "Status", "Clever", "10", "", "", "II"));
attacks.Add("Extreme Speed", new BaseAttack("Extreme Speed", "Normal", "Physical", "Cool", "5", "80", "100", "II"));
attacks.Add("Ancient Power", new BaseAttack("Ancient Power", "Rock", "Special", "Tough", "5", "60", "100", "II"));
attacks.Add("Shadow Ball", new BaseAttack("Shadow Ball", "Ghost", "Special", "Clever", "15", "80", "100", "II"));
attacks.Add("Future Sight", new BaseAttack("Future Sight", "Psychic", "Special", "Clever", "10", "120", "100", "II"));
attacks.Add("Rock Smash", new BaseAttack("Rock Smash", "Fighting", "Physical", "Tough", "15", "40", "100", "II"));
attacks.Add("Whirlpool", new BaseAttack("Whirlpool", "Water", "Special", "Beautiful", "15", "35", "85", "II"));
attacks.Add("Beat Up", new BaseAttack("Beat Up", "Dark", "Physical", "Clever", "10", "", "100", "II"));
attacks.Add("Fake Out", new BaseAttack("Fake Out", "Normal", "Physical", "Cute", "10", "40", "100", "III"));
attacks.Add("Uproar", new BaseAttack("Uproar", "Normal", "Special", "Cute", "10", "90", "100", "III"));
attacks.Add("Stockpile", new BaseAttack("Stockpile", "Normal", "Status", "Tough", "20", "", "", "III"));
attacks.Add("Spit Up", new BaseAttack("Spit Up", "Normal", "Special", "Tough", "10", "", "100", "III"));
attacks.Add("Swallow", new BaseAttack("Swallow", "Normal", "Status", "Tough", "10", "", "", "III"));
attacks.Add("Heat Wave", new BaseAttack("Heat Wave", "Fire", "Special", "Beautiful", "10", "95", "90", "III"));
attacks.Add("Hail", new BaseAttack("Hail", "Ice", "Status", "Beautiful", "10", "", "", "III"));
attacks.Add("Torment", new BaseAttack("Torment", "Dark", "Status", "Tough", "15", "", "100", "III"));
attacks.Add("Flatter", new BaseAttack("Flatter", "Dark", "Status", "Clever", "15", "", "100", "III"));
attacks.Add("Will-O-Wisp", new BaseAttack("Will-O-Wisp", "Fire", "Status", "Beautiful", "15", "", "85", "III"));
attacks.Add("Memento", new BaseAttack("Memento", "Dark", "Status", "Tough", "10", "", "100", "III"));
attacks.Add("Facade", new BaseAttack("Facade", "Normal", "Physical", "Cute", "20", "70", "100", "III"));
attacks.Add("Focus Punch", new BaseAttack("Focus Punch", "Fighting", "Physical", "Tough", "20", "150", "100", "III"));
attacks.Add("Smelling Salts", new BaseAttack("Smelling Salts", "Normal", "Physical", "Tough", "10", "70", "100", "III"));
attacks.Add("Follow Me", new BaseAttack("Follow Me", "Normal", "Status", "Cute", "20", "", "", "III"));
attacks.Add("Nature Power", new BaseAttack("Nature Power", "Normal", "Status", "Beautiful", "20", "", "", "III"));
attacks.Add("Charge", new BaseAttack("Charge", "Electric", "Status", "Clever", "20", "", "", "III"));
attacks.Add("Taunt", new BaseAttack("Taunt", "Dark", "Status", "Clever", "20", "", "100", "III"));
attacks.Add("Helping Hand", new BaseAttack("Helping Hand", "Normal", "Status", "Clever", "20", "", "", "III"));
attacks.Add("Trick", new BaseAttack("Trick", "Psychic", "Status", "Clever", "10", "", "100", "III"));
attacks.Add("Role Play", new BaseAttack("Role Play", "Psychic", "Status", "Cute", "10", "", "", "III"));
attacks.Add("Wish", new BaseAttack("Wish", "Normal", "Status", "Cute", "10", "", "", "III"));
attacks.Add("Assist", new BaseAttack("Assist", "Normal", "Status", "Cute", "20", "", "", "III"));
attacks.Add("Ingrain", new BaseAttack("Ingrain", "Grass", "Status", "Clever", "20", "", "", "III"));
attacks.Add("Superpower", new BaseAttack("Superpower", "Fighting", "Physical", "Tough", "5", "120", "100", "III"));
attacks.Add("Magic Coat", new BaseAttack("Magic Coat", "Psychic", "Status", "Beautiful", "15", "", "", "III"));
attacks.Add("Recycle", new BaseAttack("Recycle", "Normal", "Status", "Clever", "10", "", "", "III"));
attacks.Add("Revenge", new BaseAttack("Revenge", "Fighting", "Physical", "Tough", "10", "60", "100", "III"));
attacks.Add("Brick Break", new BaseAttack("Brick Break", "Fighting", "Physical", "Cool", "15", "75", "100", "III"));
attacks.Add("Yawn", new BaseAttack("Yawn", "Normal", "Status", "Cute", "10", "", "", "III"));
attacks.Add("Knock Off", new BaseAttack("Knock Off", "Dark", "Physical", "Clever", "20", "65", "100", "III"));
attacks.Add("Endeavor", new BaseAttack("Endeavor", "Normal", "Physical", "Tough", "5", "", "100", "III"));
attacks.Add("Eruption", new BaseAttack("Eruption", "Fire", "Special", "Beautiful", "5", "150", "100", "III"));
attacks.Add("Skill Swap", new BaseAttack("Skill Swap", "Psychic", "Status", "Clever", "10", "", "", "III"));
attacks.Add("Imprison", new BaseAttack("Imprison", "Psychic", "Status", "Clever", "10", "", "", "III"));
attacks.Add("Refresh", new BaseAttack("Refresh", "Normal", "Status", "Cute", "20", "", "", "III"));
attacks.Add("Grudge", new BaseAttack("Grudge", "Ghost", "Status", "Tough", "5", "", "", "III"));
attacks.Add("Snatch", new BaseAttack("Snatch", "Dark", "Status", "Clever", "10", "", "", "III"));
attacks.Add("Secret Power", new BaseAttack("Secret Power", "Normal", "Physical", "Clever", "20", "70", "100", "III"));
attacks.Add("Dive", new BaseAttack("Dive", "Water", "Physical", "Beautiful", "10", "80", "100", "III"));
attacks.Add("Arm Thrust", new BaseAttack("Arm Thrust", "Fighting", "Physical", "Tough", "20", "15", "100", "III"));
attacks.Add("Camouflage", new BaseAttack("Camouflage", "Normal", "Status", "Clever", "20", "", "", "III"));
attacks.Add("Tail Glow", new BaseAttack("Tail Glow", "Bug", "Status", "Beautiful", "20", "", "", "III"));
attacks.Add("Luster Purge", new BaseAttack("Luster Purge", "Psychic", "Special", "Clever", "5", "70", "100", "III"));
attacks.Add("Mist Ball", new BaseAttack("Mist Ball", "Psychic", "Special", "Clever", "5", "70", "100", "III"));
attacks.Add("Feather Dance", new BaseAttack("Feather Dance", "Flying", "Status", "Beautiful", "15", "", "100", "III"));
attacks.Add("Teeter Dance", new BaseAttack("Teeter Dance", "Normal", "Status", "Cute", "20", "", "100", "III"));
attacks.Add("Blaze Kick", new BaseAttack("Blaze Kick", "Fire", "Physical", "Cool", "10", "85", "90", "III"));
attacks.Add("Mud Sport", new BaseAttack("Mud Sport", "Ground", "Status", "Cute", "15", "", "", "III"));
attacks.Add("Ice Ball", new BaseAttack("Ice Ball", "Ice", "Physical", "Beautiful", "20", "30", "90", "III"));
attacks.Add("Needle Arm", new BaseAttack("Needle Arm", "Grass", "Physical", "Clever", "15", "60", "100", "III"));
attacks.Add("Slack Off", new BaseAttack("Slack Off", "Normal", "Status", "Cute", "10", "", "", "III"));
attacks.Add("Hyper Voice", new BaseAttack("Hyper Voice", "Normal", "Special", "Cool", "10", "90", "100", "III"));
attacks.Add("Poison Fang", new BaseAttack("Poison Fang", "Poison", "Physical", "Clever", "15", "50", "100", "III"));
attacks.Add("Crush Claw", new BaseAttack("Crush Claw", "Normal", "Physical", "Cool", "10", "75", "95", "III"));
attacks.Add("Blast Burn", new BaseAttack("Blast Burn", "Fire", "Special", "Beautiful", "5", "150", "90", "III"));
attacks.Add("Hydro Cannon", new BaseAttack("Hydro Cannon", "Water", "Special", "Beautiful", "5", "150", "90", "III"));
attacks.Add("Meteor Mash", new BaseAttack("Meteor Mash", "Steel", "Physical", "Cool", "10", "90", "90", "III"));
attacks.Add("Astonish", new BaseAttack("Astonish", "Ghost", "Physical", "Cute", "15", "30", "100", "III"));
attacks.Add("Weather Ball", new BaseAttack("Weather Ball", "Normal", "Special", "Beautiful", "10", "50", "100", "III"));
attacks.Add("Aromatherapy", new BaseAttack("Aromatherapy", "Grass", "Status", "Clever", "5", "", "", "III"));
attacks.Add("Fake Tears", new BaseAttack("Fake Tears", "Dark", "Status", "Cute", "20", "", "100", "III"));
attacks.Add("Air Cutter", new BaseAttack("Air Cutter", "Flying", "Special", "Cool", "25", "60", "95", "III"));
attacks.Add("Overheat", new BaseAttack("Overheat", "Fire", "Special", "Beautiful", "5", "130", "90", "III"));
attacks.Add("Odor Sleuth", new BaseAttack("Odor Sleuth", "Normal", "Status", "Clever", "40", "", "", "III"));
attacks.Add("Rock Tomb", new BaseAttack("Rock Tomb", "Rock", "Physical", "Clever", "15", "60", "95", "III"));
attacks.Add("Silver Wind", new BaseAttack("Silver Wind", "Bug", "Special", "Beautiful", "5", "60", "100", "III"));
attacks.Add("Metal Sound", new BaseAttack("Metal Sound", "Steel", "Status", "Clever", "40", "", "85", "III"));
attacks.Add("Grass Whistle", new BaseAttack("Grass Whistle", "Grass", "Status", "Clever", "15", "", "55", "III"));
attacks.Add("Tickle", new BaseAttack("Tickle", "Normal", "Status", "Cute", "20", "", "100", "III"));
attacks.Add("Cosmic Power", new BaseAttack("Cosmic Power", "Psychic", "Status", "Beautiful", "20", "", "", "III"));
attacks.Add("Water Spout", new BaseAttack("Water Spout", "Water", "Special", "Beautiful", "5", "150", "100", "III"));
attacks.Add("Signal Beam", new BaseAttack("Signal Beam", "Bug", "Special", "Beautiful", "15", "75", "100", "III"));
attacks.Add("Shadow Punch", new BaseAttack("Shadow Punch", "Ghost", "Physical", "Clever", "20", "60", "", "III"));
attacks.Add("Extrasensory", new BaseAttack("Extrasensory", "Psychic", "Special", "Cool", "20", "80", "100", "III"));
attacks.Add("Sky Uppercut", new BaseAttack("Sky Uppercut", "Fighting", "Physical", "Cool", "15", "85", "90", "III"));
attacks.Add("Sand Tomb", new BaseAttack("Sand Tomb", "Ground", "Physical", "Clever", "15", "35", "85", "III"));
attacks.Add("Sheer Cold", new BaseAttack("Sheer Cold", "Ice", "Special", "Beautiful", "5", "", "", "III"));
attacks.Add("Muddy Water", new BaseAttack("Muddy Water", "Water", "Special", "Tough", "10", "90", "85", "III"));
attacks.Add("Bullet Seed", new BaseAttack("Bullet Seed", "Grass", "Physical", "Cool", "30", "25", "100", "III"));
attacks.Add("Aerial Ace", new BaseAttack("Aerial Ace", "Flying", "Physical", "Cool", "20", "60", "", "III"));
attacks.Add("Icicle Spear", new BaseAttack("Icicle Spear", "Ice", "Physical", "Beautiful", "30", "25", "100", "III"));
attacks.Add("Iron Defense", new BaseAttack("Iron Defense", "Steel", "Status", "Tough", "15", "", "", "III"));
attacks.Add("Block", new BaseAttack("Block", "Normal", "Status", "Cute", "5", "", "", "III"));
attacks.Add("Howl", new BaseAttack("Howl", "Normal", "Status", "Cool", "40", "", "", "III"));
attacks.Add("Dragon Claw", new BaseAttack("Dragon Claw", "Dragon", "Physical", "Cool", "15", "80", "100", "III"));
attacks.Add("Frenzy Plant", new BaseAttack("Frenzy Plant", "Grass", "Special", "Cool", "5", "150", "90", "III"));
attacks.Add("Bulk Up", new BaseAttack("Bulk Up", "Fighting", "Status", "Cool", "20", "", "", "III"));
attacks.Add("Bounce", new BaseAttack("Bounce", "Flying", "Physical", "Cute", "5", "85", "85", "III"));
attacks.Add("Mud Shot", new BaseAttack("Mud Shot", "Ground", "Special", "Tough", "15", "55", "95", "III"));
attacks.Add("Poison Tail", new BaseAttack("Poison Tail", "Poison", "Physical", "Clever", "25", "50", "100", "III"));
attacks.Add("Covet", new BaseAttack("Covet", "Normal", "Physical", "Cute", "25", "60", "100", "III"));
attacks.Add("Volt Tackle", new BaseAttack("Volt Tackle", "Electric", "Physical", "Cool", "15", "120", "100", "III"));
attacks.Add("Magical Leaf", new BaseAttack("Magical Leaf", "Grass", "Special", "Beautiful", "20", "60", "", "III"));
attacks.Add("Water Sport", new BaseAttack("Water Sport", "Water", "Status", "Cute", "15", "", "", "III"));
attacks.Add("Calm Mind", new BaseAttack("Calm Mind", "Psychic", "Status", "Clever", "20", "", "", "III"));
attacks.Add("Leaf Blade", new BaseAttack("Leaf Blade", "Grass", "Physical", "Cool", "15", "90", "100", "III"));
attacks.Add("Dragon Dance", new BaseAttack("Dragon Dance", "Dragon", "Status", "Cool", "20", "", "", "III"));
attacks.Add("Rock Blast", new BaseAttack("Rock Blast", "Rock", "Physical", "Tough", "10", "25", "90", "III"));
attacks.Add("Shock Wave", new BaseAttack("Shock Wave", "Electric", "Special", "Cool", "20", "60", "", "III"));
attacks.Add("Water Pulse", new BaseAttack("Water Pulse", "Water", "Special", "Beautiful", "20", "60", "100", "III"));
attacks.Add("Doom Desire", new BaseAttack("Doom Desire", "Steel", "Special", "Beautiful", "5", "140", "100", "III"));
attacks.Add("Psycho Boost", new BaseAttack("Psycho Boost", "Psychic", "Special", "Clever", "5", "140", "90", "III"));
attacks.Add("Roost", new BaseAttack("Roost", "Flying", "Status", "Clever", "10", "", "", "IV"));
attacks.Add("Gravity", new BaseAttack("Gravity", "Psychic", "Status", "Clever", "5", "", "", "IV"));
attacks.Add("Miracle Eye", new BaseAttack("Miracle Eye", "Psychic", "Status", "Clever", "40", "", "", "IV"));
attacks.Add("Wake-Up Slap", new BaseAttack("Wake-Up Slap", "Fighting", "Physical", "Tough", "10", "70", "100", "IV"));
attacks.Add("Hammer Arm", new BaseAttack("Hammer Arm", "Fighting", "Physical", "Tough", "10", "100", "90", "IV"));
attacks.Add("Gyro Ball", new BaseAttack("Gyro Ball", "Steel", "Physical", "Cool", "5", "", "100", "IV"));
attacks.Add("Healing Wish", new BaseAttack("Healing Wish", "Psychic", "Status", "Beautiful", "10", "", "", "IV"));
attacks.Add("Brine", new BaseAttack("Brine", "Water", "Special", "Tough", "10", "65", "100", "IV"));
attacks.Add("Natural Gift", new BaseAttack("Natural Gift", "Normal", "Physical", "Clever", "15", "", "100", "IV"));
attacks.Add("Feint", new BaseAttack("Feint", "Normal", "Physical", "Clever", "10", "30", "100", "IV"));
attacks.Add("Pluck", new BaseAttack("Pluck", "Flying", "Physical", "Cute", "20", "60", "100", "IV"));
attacks.Add("Tailwind", new BaseAttack("Tailwind", "Flying", "Status", "Cool", "15", "", "", "IV"));
attacks.Add("Acupressure", new BaseAttack("Acupressure", "Normal", "Status", "Tough", "30", "", "", "IV"));
attacks.Add("Metal Burst", new BaseAttack("Metal Burst", "Steel", "Physical", "Cool", "10", "", "100", "IV"));
attacks.Add("U-turn", new BaseAttack("U-turn", "Bug", "Physical", "Cute", "20", "70", "100", "IV"));
attacks.Add("Close Combat", new BaseAttack("Close Combat", "Fighting", "Physical", "Tough", "5", "120", "100", "IV"));
attacks.Add("Payback", new BaseAttack("Payback", "Dark", "Physical", "Tough", "10", "50", "100", "IV"));
attacks.Add("Assurance", new BaseAttack("Assurance", "Dark", "Physical", "Clever", "10", "60", "100", "IV"));
attacks.Add("Embargo", new BaseAttack("Embargo", "Dark", "Status", "Clever", "15", "", "100", "IV"));
attacks.Add("Fling", new BaseAttack("Fling", "Dark", "Physical", "Cute", "10", "", "100", "IV"));
attacks.Add("Psycho Shift", new BaseAttack("Psycho Shift", "Psychic", "Status", "Clever", "10", "", "100", "IV"));
attacks.Add("Trump Card", new BaseAttack("Trump Card", "Normal", "Special", "Cool", "5", "", "", "IV"));
attacks.Add("Heal Block", new BaseAttack("Heal Block", "Psychic", "Status", "Clever", "15", "", "100", "IV"));
attacks.Add("Wring Out", new BaseAttack("Wring Out", "Normal", "Special", "Tough", "5", "", "100", "IV"));
attacks.Add("Power Trick", new BaseAttack("Power Trick", "Psychic", "Status", "Clever", "10", "", "", "IV"));
attacks.Add("Gastro Acid", new BaseAttack("Gastro Acid", "Poison", "Status", "Tough", "10", "", "100", "IV"));
attacks.Add("Lucky Chant", new BaseAttack("Lucky Chant", "Normal", "Status", "Cute", "30", "", "", "IV"));
attacks.Add("Me First", new BaseAttack("Me First", "Normal", "Status", "Clever", "20", "", "", "IV"));
attacks.Add("Copycat", new BaseAttack("Copycat", "Normal", "Status", "Cute", "20", "", "", "IV"));
attacks.Add("Power Swap", new BaseAttack("Power Swap", "Psychic", "Status", "Clever", "10", "", "", "IV"));
attacks.Add("Guard Swap", new BaseAttack("Guard Swap", "Psychic", "Status", "Clever", "10", "", "", "IV"));
attacks.Add("Punishment", new BaseAttack("Punishment", "Dark", "Physical", "Cool", "5", "", "100", "IV"));
attacks.Add("Last Resort", new BaseAttack("Last Resort", "Normal", "Physical", "Cute", "5", "140", "100", "IV"));
attacks.Add("Worry Seed", new BaseAttack("Worry Seed", "Grass", "Status", "Clever", "10", "", "100", "IV"));
attacks.Add("Sucker Punch", new BaseAttack("Sucker Punch", "Dark", "Physical", "Clever", "5", "70", "100", "IV"));
attacks.Add("Toxic Spikes", new BaseAttack("Toxic Spikes", "Poison", "Status", "Clever", "20", "", "", "IV"));
attacks.Add("Heart Swap", new BaseAttack("Heart Swap", "Psychic", "Status", "Clever", "10", "", "", "IV"));
attacks.Add("Aqua Ring", new BaseAttack("Aqua Ring", "Water", "Status", "Beautiful", "20", "", "", "IV"));
attacks.Add("Magnet Rise", new BaseAttack("Magnet Rise", "Electric", "Status", "Clever", "10", "", "", "IV"));
attacks.Add("Flare Blitz", new BaseAttack("Flare Blitz", "Fire", "Physical", "Cool", "15", "120", "100", "IV"));
attacks.Add("Force Palm", new BaseAttack("Force Palm", "Fighting", "Physical", "Cool", "10", "60", "100", "IV"));
attacks.Add("Aura Sphere", new BaseAttack("Aura Sphere", "Fighting", "Special", "Beautiful", "20", "80", "", "IV"));
attacks.Add("Rock Polish", new BaseAttack("Rock Polish", "Rock", "Status", "Tough", "20", "", "", "IV"));
attacks.Add("Poison Jab", new BaseAttack("Poison Jab", "Poison", "Physical", "Tough", "20", "80", "100", "IV"));
attacks.Add("Dark Pulse", new BaseAttack("Dark Pulse", "Dark", "Special", "Cool", "15", "80", "100", "IV"));
attacks.Add("Night Slash", new BaseAttack("Night Slash", "Dark", "Physical", "Cool", "15", "70", "100", "IV"));
attacks.Add("Aqua Tail", new BaseAttack("Aqua Tail", "Water", "Physical", "Beautiful", "10", "90", "90", "IV"));
attacks.Add("Seed Bomb", new BaseAttack("Seed Bomb", "Grass", "Physical", "Tough", "15", "80", "100", "IV"));
attacks.Add("Air Slash", new BaseAttack("Air Slash", "Flying", "Special", "Cool", "15", "75", "95", "IV"));
attacks.Add("X-Scissor", new BaseAttack("X-Scissor", "Bug", "Physical", "Cool", "15", "80", "100", "IV"));
attacks.Add("Bug Buzz", new BaseAttack("Bug Buzz", "Bug", "Special", "Beautiful", "10", "90", "100", "IV"));
attacks.Add("Dragon Pulse", new BaseAttack("Dragon Pulse", "Dragon", "Special", "Beautiful", "10", "85", "100", "IV"));
attacks.Add("Dragon Rush", new BaseAttack("Dragon Rush", "Dragon", "Physical", "Tough", "10", "100", "75", "IV"));
attacks.Add("Power Gem", new BaseAttack("Power Gem", "Rock", "Special", "Beautiful", "20", "80", "100", "IV"));
attacks.Add("Drain Punch", new BaseAttack("Drain Punch", "Fighting", "Physical", "Tough", "10", "75", "100", "IV"));
attacks.Add("Vacuum Wave", new BaseAttack("Vacuum Wave", "Fighting", "Special", "Cool", "30", "40", "100", "IV"));
attacks.Add("Focus Blast", new BaseAttack("Focus Blast", "Fighting", "Special", "Cool", "5", "120", "70", "IV"));
attacks.Add("Energy Ball", new BaseAttack("Energy Ball", "Grass", "Special", "Beautiful", "10", "90", "100", "IV"));
attacks.Add("Brave Bird", new BaseAttack("Brave Bird", "Flying", "Physical", "Cool", "15", "120", "100", "IV"));
attacks.Add("Earth Power", new BaseAttack("Earth Power", "Ground", "Special", "Beautiful", "10", "90", "100", "IV"));
attacks.Add("Switcheroo", new BaseAttack("Switcheroo", "Dark", "Status", "Clever", "10", "", "100", "IV"));
attacks.Add("Giga Impact", new BaseAttack("Giga Impact", "Normal", "Physical", "Tough", "5", "150", "90", "IV"));
attacks.Add("Nasty Plot", new BaseAttack("Nasty Plot", "Dark", "Status", "Clever", "20", "", "", "IV"));
attacks.Add("Bullet Punch", new BaseAttack("Bullet Punch", "Steel", "Physical", "Tough", "30", "40", "100", "IV"));
attacks.Add("Avalanche", new BaseAttack("Avalanche", "Ice", "Physical", "Beautiful", "10", "60", "100", "IV"));
attacks.Add("Ice Shard", new BaseAttack("Ice Shard", "Ice", "Physical", "Beautiful", "30", "40", "100", "IV"));
attacks.Add("Shadow Claw", new BaseAttack("Shadow Claw", "Ghost", "Physical", "Cool", "15", "70", "100", "IV"));
attacks.Add("Thunder Fang", new BaseAttack("Thunder Fang", "Electric", "Physical", "Cool", "15", "65", "95", "IV"));
attacks.Add("Ice Fang", new BaseAttack("Ice Fang", "Ice", "Physical", "Cool", "15", "65", "95", "IV"));
attacks.Add("Fire Fang", new BaseAttack("Fire Fang", "Fire", "Physical", "Cool", "15", "65", "95", "IV"));
attacks.Add("Shadow Sneak", new BaseAttack("Shadow Sneak", "Ghost", "Physical", "Clever", "30", "40", "100", "IV"));
attacks.Add("Mud Bomb", new BaseAttack("Mud Bomb", "Ground", "Special", "Cute", "10", "65", "85", "IV"));
attacks.Add("Psycho Cut", new BaseAttack("Psycho Cut", "Psychic", "Physical", "Cool", "20", "70", "100", "IV"));
attacks.Add("Zen Headbutt", new BaseAttack("Zen Headbutt", "Psychic", "Physical", "Clever", "15", "80", "90", "IV"));
attacks.Add("Mirror Shot", new BaseAttack("Mirror Shot", "Steel", "Special", "Beautiful", "10", "65", "85", "IV"));
attacks.Add("Flash Cannon", new BaseAttack("Flash Cannon", "Steel", "Special", "Beautiful", "10", "80", "100", "IV"));
attacks.Add("Rock Climb", new BaseAttack("Rock Climb", "Normal", "Physical", "Tough", "20", "90", "85", "IV"));
attacks.Add("Defog", new BaseAttack("Defog", "Flying", "Status", "Cool", "15", "", "", "IV"));
attacks.Add("Trick Room", new BaseAttack("Trick Room", "Psychic", "Status", "Clever", "5", "", "", "IV"));
attacks.Add("Draco Meteor", new BaseAttack("Draco Meteor", "Dragon", "Special", "Beautiful", "5", "130", "90", "IV"));
attacks.Add("Discharge", new BaseAttack("Discharge", "Electric", "Special", "Beautiful", "15", "80", "100", "IV"));
attacks.Add("Lava Plume", new BaseAttack("Lava Plume", "Fire", "Special", "Tough", "15", "80", "100", "IV"));
attacks.Add("Leaf Storm", new BaseAttack("Leaf Storm", "Grass", "Special", "Beautiful", "5", "130", "90", "IV"));
attacks.Add("Power Whip", new BaseAttack("Power Whip", "Grass", "Physical", "Tough", "10", "120", "85", "IV"));
attacks.Add("Rock Wrecker", new BaseAttack("Rock Wrecker", "Rock", "Physical", "Tough", "5", "150", "90", "IV"));
attacks.Add("Cross Poison", new BaseAttack("Cross Poison", "Poison", "Physical", "Cool", "20", "70", "100", "IV"));
attacks.Add("Gunk Shot", new BaseAttack("Gunk Shot", "Poison", "Physical", "Tough", "5", "120", "80", "IV"));
attacks.Add("Iron Head", new BaseAttack("Iron Head", "Steel", "Physical", "Tough", "15", "80", "100", "IV"));
attacks.Add("Magnet Bomb", new BaseAttack("Magnet Bomb", "Steel", "Physical", "Cool", "20", "60", "", "IV"));
attacks.Add("Stone Edge", new BaseAttack("Stone Edge", "Rock", "Physical", "Tough", "5", "100", "80", "IV"));
attacks.Add("Captivate", new BaseAttack("Captivate", "Normal", "Status", "Cute", "20", "", "100", "IV"));
attacks.Add("Stealth Rock", new BaseAttack("Stealth Rock", "Rock", "Status", "Cool", "20", "", "", "IV"));
attacks.Add("Grass Knot", new BaseAttack("Grass Knot", "Grass", "Special", "Cute", "20", "", "100", "IV"));
attacks.Add("Chatter", new BaseAttack("Chatter", "Flying", "Special", "Cute", "20", "65", "100", "IV"));
attacks.Add("Judgment", new BaseAttack("Judgment", "Normal", "Special", "Beautiful", "10", "100", "100", "IV"));
attacks.Add("Bug Bite", new BaseAttack("Bug Bite", "Bug", "Physical", "Cute", "20", "60", "100", "IV"));
attacks.Add("Charge Beam", new BaseAttack("Charge Beam", "Electric", "Special", "Beautiful", "10", "50", "90", "IV"));
attacks.Add("Wood Hammer", new BaseAttack("Wood Hammer", "Grass", "Physical", "Tough", "15", "120", "100", "IV"));
attacks.Add("Aqua Jet", new BaseAttack("Aqua Jet", "Water", "Physical", "Cool", "20", "40", "100", "IV"));
attacks.Add("Attack Order", new BaseAttack("Attack Order", "Bug", "Physical", "Clever", "15", "90", "100", "IV"));
attacks.Add("Defend Order", new BaseAttack("Defend Order", "Bug", "Status", "Clever", "10", "", "", "IV"));
attacks.Add("Heal Order", new BaseAttack("Heal Order", "Bug", "Status", "Clever", "10", "", "", "IV"));
attacks.Add("Head Smash", new BaseAttack("Head Smash", "Rock", "Physical", "Tough", "5", "150", "80", "IV"));
attacks.Add("Double Hit", new BaseAttack("Double Hit", "Normal", "Physical", "Cool", "10", "35", "90", "IV"));
attacks.Add("Roar of Time", new BaseAttack("Roar of Time", "Dragon", "Special", "Beautiful", "5", "150", "90", "IV"));
attacks.Add("Spacial Rend", new BaseAttack("Spacial Rend", "Dragon", "Special", "Beautiful", "5", "100", "95", "IV"));
attacks.Add("Lunar Dance", new BaseAttack("Lunar Dance", "Psychic", "Status", "Beautiful", "10", "", "", "IV"));
attacks.Add("Crush Grip", new BaseAttack("Crush Grip", "Normal", "Physical", "Tough", "5", "", "100", "IV"));
attacks.Add("Magma Storm", new BaseAttack("Magma Storm", "Fire", "Special", "Tough", "5", "100", "75", "IV"));
attacks.Add("Dark Void", new BaseAttack("Dark Void", "Dark", "Status", "Clever", "10", "", "50", "IV"));
attacks.Add("Seed Flare", new BaseAttack("Seed Flare", "Grass", "Special", "Beautiful", "5", "120", "85", "IV"));
attacks.Add("Ominous Wind", new BaseAttack("Ominous Wind", "Ghost", "Special", "Beautiful", "5", "60", "100", "IV"));
attacks.Add("Shadow Force", new BaseAttack("Shadow Force", "Ghost", "Physical", "Cool", "5", "120", "100", "IV"));
attacks.Add("Hone Claws", new BaseAttack("Hone Claws", "Dark", "Status", "Cute", "15", "", "", "V"));
attacks.Add("Wide Guard", new BaseAttack("Wide Guard", "Rock", "Status", "Tough", "10", "", "", "V"));
attacks.Add("Guard Split", new BaseAttack("Guard Split", "Psychic", "Status", "Clever", "10", "", "", "V"));
attacks.Add("Power Split", new BaseAttack("Power Split", "Psychic", "Status", "Clever", "10", "", "", "V"));
attacks.Add("Wonder Room", new BaseAttack("Wonder Room", "Psychic", "Status", "Clever", "10", "", "", "V"));
attacks.Add("Psyshock", new BaseAttack("Psyshock", "Psychic", "Special", "Beautiful", "10", "80", "100", "V"));
attacks.Add("Venoshock", new BaseAttack("Venoshock", "Poison", "Special", "Beautiful", "10", "65", "100", "V"));
attacks.Add("Autotomize", new BaseAttack("Autotomize", "Steel", "Status", "Beautiful", "15", "", "", "V"));
attacks.Add("Rage Powder", new BaseAttack("Rage Powder", "Bug", "Status", "Clever", "20", "", "", "V"));
attacks.Add("Telekinesis", new BaseAttack("Telekinesis", "Psychic", "Status", "Clever", "15", "", "", "V"));
attacks.Add("Magic Room", new BaseAttack("Magic Room", "Psychic", "Status", "Clever", "10", "", "", "V"));
attacks.Add("Smack Down", new BaseAttack("Smack Down", "Rock", "Physical", "Tough", "15", "50", "100", "V"));
attacks.Add("Storm Throw", new BaseAttack("Storm Throw", "Fighting", "Physical", "Cool", "10", "60", "100", "V"));
attacks.Add("Flame Burst", new BaseAttack("Flame Burst", "Fire", "Special", "Beautiful", "15", "70", "100", "V"));
attacks.Add("Sludge Wave", new BaseAttack("Sludge Wave", "Poison", "Special", "Tough", "10", "95", "100", "V"));
attacks.Add("Quiver Dance", new BaseAttack("Quiver Dance", "Bug", "Status", "Beautiful", "20", "", "", "V"));
attacks.Add("Heavy Slam", new BaseAttack("Heavy Slam", "Steel", "Physical", "Tough", "10", "", "100", "V"));
attacks.Add("Synchronoise", new BaseAttack("Synchronoise", "Psychic", "Special", "Clever", "10", "120", "100", "V"));
attacks.Add("Electro Ball", new BaseAttack("Electro Ball", "Electric", "Special", "Cool", "10", "", "100", "V"));
attacks.Add("Soak", new BaseAttack("Soak", "Water", "Status", "Cute", "20", "", "100", "V"));
attacks.Add("Flame Charge", new BaseAttack("Flame Charge", "Fire", "Physical", "Cool", "20", "50", "100", "V"));
attacks.Add("Coil", new BaseAttack("Coil", "Poison", "Status", "Tough", "20", "", "", "V"));
attacks.Add("Low Sweep", new BaseAttack("Low Sweep", "Fighting", "Physical", "Clever", "20", "65", "100", "V"));
attacks.Add("Acid Spray", new BaseAttack("Acid Spray", "Poison", "Special", "Beautiful", "20", "40", "100", "V"));
attacks.Add("Foul Play", new BaseAttack("Foul Play", "Dark", "Physical", "Clever", "15", "95", "100", "V"));
attacks.Add("Simple Beam", new BaseAttack("Simple Beam", "Normal", "Status", "Cute", "15", "", "100", "V"));
attacks.Add("Entrainment", new BaseAttack("Entrainment", "Normal", "Status", "Cute", "15", "", "100", "V"));
attacks.Add("After You", new BaseAttack("After You", "Normal", "Status", "Cute", "15", "", "", "V"));
attacks.Add("Round", new BaseAttack("Round", "Normal", "Special", "Beautiful", "15", "60", "100", "V"));
attacks.Add("Echoed Voice", new BaseAttack("Echoed Voice", "Normal", "Special", "Beautiful", "15", "40", "100", "V"));
attacks.Add("Chip Away", new BaseAttack("Chip Away", "Normal", "Physical", "Tough", "20", "70", "100", "V"));
attacks.Add("Clear Smog", new BaseAttack("Clear Smog", "Poison", "Special", "Beautiful", "15", "50", "", "V"));
attacks.Add("Stored Power", new BaseAttack("Stored Power", "Psychic", "Special", "Clever", "10", "20", "100", "V"));
attacks.Add("Quick Guard", new BaseAttack("Quick Guard", "Fighting", "Status", "Cool", "15", "", "", "V"));
attacks.Add("Ally Switch", new BaseAttack("Ally Switch", "Psychic", "Status", "Clever", "15", "", "", "V"));
attacks.Add("Scald", new BaseAttack("Scald", "Water", "Special", "Tough", "15", "80", "100", "V"));
attacks.Add("Shell Smash", new BaseAttack("Shell Smash", "Normal", "Status", "Tough", "15", "", "", "V"));
attacks.Add("Heal Pulse", new BaseAttack("Heal Pulse", "Psychic", "Status", "Beautiful", "10", "", "", "V"));
attacks.Add("Hex", new BaseAttack("Hex", "Ghost", "Special", "Clever", "10", "65", "100", "V"));
attacks.Add("Sky Drop", new BaseAttack("Sky Drop", "Flying", "Physical", "Tough", "10", "60", "100", "V"));
attacks.Add("Shift Gear", new BaseAttack("Shift Gear", "Steel", "Status", "Clever", "10", "", "", "V"));
attacks.Add("Circle Throw", new BaseAttack("Circle Throw", "Fighting", "Physical", "Cool", "10", "60", "90", "V"));
attacks.Add("Incinerate", new BaseAttack("Incinerate", "Fire", "Special", "Tough", "15", "60", "100", "V"));
attacks.Add("Quash", new BaseAttack("Quash", "Dark", "Status", "Clever", "15", "", "100", "V"));
attacks.Add("Acrobatics", new BaseAttack("Acrobatics", "Flying", "Physical", "Cool", "15", "55", "100", "V"));
attacks.Add("Reflect Type", new BaseAttack("Reflect Type", "Normal", "Status", "Clever", "15", "", "", "V"));
attacks.Add("Retaliate", new BaseAttack("Retaliate", "Normal", "Physical", "Cool", "5", "70", "100", "V"));
attacks.Add("Final Gambit", new BaseAttack("Final Gambit", "Fighting", "Special", "Tough", "5", "", "100", "V"));
attacks.Add("Bestow", new BaseAttack("Bestow", "Normal", "Status", "Cute", "15", "", "", "V"));
attacks.Add("Inferno", new BaseAttack("Inferno", "Fire", "Special", "Beautiful", "5", "100", "50", "V"));
attacks.Add("Water Pledge", new BaseAttack("Water Pledge", "Water", "Special", "Beautiful", "10", "80", "100", "V"));
attacks.Add("Fire Pledge", new BaseAttack("Fire Pledge", "Fire", "Special", "Beautiful", "10", "80", "100", "V"));
attacks.Add("Grass Pledge", new BaseAttack("Grass Pledge", "Grass", "Special", "Beautiful", "10", "80", "100", "V"));
attacks.Add("Volt Switch", new BaseAttack("Volt Switch", "Electric", "Special", "Cool", "20", "70", "100", "V"));
attacks.Add("Struggle Bug", new BaseAttack("Struggle Bug", "Bug", "Special", "Cute", "20", "50", "100", "V"));
attacks.Add("Bulldoze", new BaseAttack("Bulldoze", "Ground", "Physical", "Tough", "20", "60", "100", "V"));
attacks.Add("Frost Breath", new BaseAttack("Frost Breath", "Ice", "Special", "Beautiful", "10", "60", "90", "V"));
attacks.Add("Dragon Tail", new BaseAttack("Dragon Tail", "Dragon", "Physical", "Tough", "10", "60", "90", "V"));
attacks.Add("Work Up", new BaseAttack("Work Up", "Normal", "Status", "Tough", "30", "", "", "V"));
attacks.Add("Electroweb", new BaseAttack("Electroweb", "Electric", "Special", "Beautiful", "15", "55", "95", "V"));
attacks.Add("Wild Charge", new BaseAttack("Wild Charge", "Electric", "Physical", "Tough", "15", "90", "100", "V"));
attacks.Add("Drill Run", new BaseAttack("Drill Run", "Ground", "Physical", "Tough", "10", "80", "95", "V"));
attacks.Add("Dual Chop", new BaseAttack("Dual Chop", "Dragon", "Physical", "Tough", "15", "40", "90", "V"));
attacks.Add("Heart Stamp", new BaseAttack("Heart Stamp", "Psychic", "Physical", "Cute", "25", "60", "100", "V"));
attacks.Add("Horn Leech", new BaseAttack("Horn Leech", "Grass", "Physical", "Tough", "10", "75", "100", "V"));
attacks.Add("Sacred Sword", new BaseAttack("Sacred Sword", "Fighting", "Physical", "Cool", "15", "90", "100", "V"));
attacks.Add("Razor Shell", new BaseAttack("Razor Shell", "Water", "Physical", "Cool", "10", "75", "95", "V"));
attacks.Add("Heat Crash", new BaseAttack("Heat Crash", "Fire", "Physical", "Tough", "10", "", "100", "V"));
attacks.Add("Leaf Tornado", new BaseAttack("Leaf Tornado", "Grass", "Special", "Cool", "10", "65", "90", "V"));
attacks.Add("Steamroller", new BaseAttack("Steamroller", "Bug", "Physical", "Tough", "20", "65", "100", "V"));
attacks.Add("Cotton Guard", new BaseAttack("Cotton Guard", "Grass", "Status", "Cute", "10", "", "", "V"));
attacks.Add("Night Daze", new BaseAttack("Night Daze", "Dark", "Special", "Cool", "10", "85", "95", "V"));
attacks.Add("Psystrike", new BaseAttack("Psystrike", "Psychic", "Special", "Cool", "10", "100", "100", "V"));
attacks.Add("Tail Slap", new BaseAttack("Tail Slap", "Normal", "Physical", "Cute", "10", "25", "85", "V"));
attacks.Add("Hurricane", new BaseAttack("Hurricane", "Flying", "Special", "Tough", "10", "110", "70", "V"));
attacks.Add("Head Charge", new BaseAttack("Head Charge", "Normal", "Physical", "Tough", "15", "120", "100", "V"));
attacks.Add("Gear Grind", new BaseAttack("Gear Grind", "Steel", "Physical", "Clever", "15", "50", "85", "V"));
attacks.Add("Searing Shot", new BaseAttack("Searing Shot", "Fire", "Special", "Cool", "5", "100", "100", "V"));
attacks.Add("Techno Blast", new BaseAttack("Techno Blast", "Normal", "Special", "Cool", "5", "120", "100", "V"));
attacks.Add("Relic Song", new BaseAttack("Relic Song", "Normal", "Special", "Beautiful", "10", "75", "100", "V"));
attacks.Add("Secret Sword", new BaseAttack("Secret Sword", "Fighting", "Special", "Beautiful", "10", "85", "100", "V"));
attacks.Add("Glaciate", new BaseAttack("Glaciate", "Ice", "Special", "Beautiful", "10", "65", "95", "V"));
attacks.Add("Bolt Strike", new BaseAttack("Bolt Strike", "Electric", "Physical", "Beautiful", "5", "130", "85", "V"));
attacks.Add("Blue Flare", new BaseAttack("Blue Flare", "Fire", "Special", "Beautiful", "5", "130", "85", "V"));
attacks.Add("Fiery Dance", new BaseAttack("Fiery Dance", "Fire", "Special", "Beautiful", "10", "80", "100", "V"));
attacks.Add("Freeze Shock", new BaseAttack("Freeze Shock", "Ice", "Physical", "Beautiful", "5", "140", "90", "V"));
attacks.Add("Ice Burn", new BaseAttack("Ice Burn", "Ice", "Special", "Beautiful", "5", "140", "90", "V"));
attacks.Add("Snarl", new BaseAttack("Snarl", "Dark", "Special", "Tough", "15", "55", "95", "V"));
attacks.Add("Icicle Crash", new BaseAttack("Icicle Crash", "Ice", "Physical", "Beautiful", "10", "85", "90", "V"));
attacks.Add("V-create", new BaseAttack("V-create", "Fire", "Physical", "Cool", "5", "180", "95", "V"));
attacks.Add("Fusion Flare", new BaseAttack("Fusion Flare", "Fire", "Special", "Beautiful", "5", "100", "100", "V"));
attacks.Add("Fusion Bolt", new BaseAttack("Fusion Bolt", "Electric", "Physical", "Cool", "5", "100", "100", "V"));
attacks.Add("Flying Press", new BaseAttack("Flying Press", "Fighting", "Physical", "Tough", "10", "100", "95", "VI"));
attacks.Add("Mat Block", new BaseAttack("Mat Block", "Fighting", "Status", "Cool", "10", "", "", "VI"));
attacks.Add("Belch", new BaseAttack("Belch", "Poison", "Special", "Tough", "10", "120", "90", "VI"));
attacks.Add("Rototiller", new BaseAttack("Rototiller", "Ground", "Status", "Tough", "10", "", "", "VI"));
attacks.Add("Sticky Web", new BaseAttack("Sticky Web", "Bug", "Status", "Tough", "20", "", "", "VI"));
attacks.Add("Fell Stinger", new BaseAttack("Fell Stinger", "Bug", "Physical", "Cool", "25", "50", "100", "VI"));
attacks.Add("Phantom Force", new BaseAttack("Phantom Force", "Ghost", "Physical", "Cool", "10", "90", "100", "VI"));
attacks.Add("Trick-or-Treat", new BaseAttack("Trick-or-Treat", "Ghost", "Status", "Cute", "20", "", "100", "VI"));
attacks.Add("Noble Roar", new BaseAttack("Noble Roar", "Normal", "Status", "Tough", "30", "", "100", "VI"));
attacks.Add("Ion Deluge", new BaseAttack("Ion Deluge", "Electric", "Status", "Beautiful", "25", "", "", "VI"));
attacks.Add("Parabolic Charge", new BaseAttack("Parabolic Charge", "Electric", "Special", "Clever", "20", "65", "100", "VI"));
attacks.Add("Forest's Curse", new BaseAttack("Forest's Curse", "Grass", "Status", "Clever", "20", "", "100", "VI"));
attacks.Add("Petal Blizzard", new BaseAttack("Petal Blizzard", "Grass", "Physical", "Beautiful", "15", "90", "100", "VI"));
attacks.Add("Freeze-Dry", new BaseAttack("Freeze-Dry", "Ice", "Special", "Beautiful", "20", "70", "100", "VI"));
attacks.Add("Disarming Voice", new BaseAttack("Disarming Voice", "Fairy", "Special", "Cute", "15", "40", "", "VI"));
attacks.Add("Parting Shot", new BaseAttack("Parting Shot", "Dark", "Status", "Cool", "20", "", "100", "VI"));
attacks.Add("Topsy-Turvy", new BaseAttack("Topsy-Turvy", "Dark", "Status", "Clever", "20", "", "", "VI"));
attacks.Add("Draining Kiss", new BaseAttack("Draining Kiss", "Fairy", "Special", "Cute", "10", "50", "100", "VI"));
attacks.Add("Crafty Shield", new BaseAttack("Crafty Shield", "Fairy", "Status", "Clever", "10", "", "", "VI"));
attacks.Add("Flower Shield", new BaseAttack("Flower Shield", "Fairy", "Status", "Beautiful", "10", "", "", "VI"));
attacks.Add("Grassy Terrain", new BaseAttack("Grassy Terrain", "Grass", "Status", "Beautiful", "10", "", "", "VI"));
attacks.Add("Misty Terrain", new BaseAttack("Misty Terrain", "Fairy", "Status", "Beautiful", "10", "", "", "VI"));
attacks.Add("Electrify", new BaseAttack("Electrify", "Electric", "Status", "Clever", "20", "", "", "VI"));
attacks.Add("Play Rough", new BaseAttack("Play Rough", "Fairy", "Physical", "Cute", "10", "90", "90", "VI"));
attacks.Add("Fairy Wind", new BaseAttack("Fairy Wind", "Fairy", "Special", "Beautiful", "30", "40", "100", "VI"));
attacks.Add("Moonblast", new BaseAttack("Moonblast", "Fairy", "Special", "Beautiful", "15", "95", "100", "VI"));
attacks.Add("Boomburst", new BaseAttack("Boomburst", "Normal", "Special", "Tough", "10", "140", "100", "VI"));
attacks.Add("Fairy Lock", new BaseAttack("Fairy Lock", "Fairy", "Status", "Clever", "10", "", "", "VI"));
attacks.Add("King's Shield", new BaseAttack("King's Shield", "Steel", "Status", "Cool", "10", "", "", "VI"));
attacks.Add("Play Nice", new BaseAttack("Play Nice", "Normal", "Status", "Cute", "20", "", "", "VI"));
attacks.Add("Confide", new BaseAttack("Confide", "Normal", "Status", "Cute", "20", "", "", "VI"));
attacks.Add("Diamond Storm", new BaseAttack("Diamond Storm", "Rock", "Physical", "Beautiful", "5", "100", "95", "VI"));
attacks.Add("Steam Eruption", new BaseAttack("Steam Eruption", "Water", "Special", "Beautiful", "5", "110", "95", "VI"));
attacks.Add("Hyperspace Hole", new BaseAttack("Hyperspace Hole", "Psychic", "Special", "Clever", "5", "80", "", "VI"));
attacks.Add("Water Shuriken", new BaseAttack("Water Shuriken", "Water", "Special", "Cool", "20", "15", "100", "VI"));
attacks.Add("Mystical Fire", new BaseAttack("Mystical Fire", "Fire", "Special", "Beautiful", "10", "75", "100", "VI"));
attacks.Add("Spiky Shield", new BaseAttack("Spiky Shield", "Grass", "Status", "Tough", "10", "", "", "VI"));
attacks.Add("Aromatic Mist", new BaseAttack("Aromatic Mist", "Fairy", "Status", "Beautiful", "20", "", "", "VI"));
attacks.Add("Eerie Impulse", new BaseAttack("Eerie Impulse", "Electric", "Status", "Clever", "15", "", "100", "VI"));
attacks.Add("Venom Drench", new BaseAttack("Venom Drench", "Poison", "Status", "Clever", "20", "", "100", "VI"));
attacks.Add("Powder", new BaseAttack("Powder", "Bug", "Status", "Clever", "20", "", "100", "VI"));
attacks.Add("Geomancy", new BaseAttack("Geomancy", "Fairy", "Status", "Beautiful", "10", "", "", "VI"));
attacks.Add("Magnetic Flux", new BaseAttack("Magnetic Flux", "Electric", "Status", "Clever", "20", "", "", "VI"));
attacks.Add("Happy Hour", new BaseAttack("Happy Hour", "Normal", "Status", "Cute", "30", "", "", "VI"));
attacks.Add("Electric Terrain", new BaseAttack("Electric Terrain", "Electric", "Status", "Clever", "10", "", "", "VI"));
attacks.Add("Dazzling Gleam", new BaseAttack("Dazzling Gleam", "Fairy", "Special", "Beautiful", "10", "80", "100", "VI"));
attacks.Add("Celebrate", new BaseAttack("Celebrate", "Normal", "Status", "Cute", "40", "", "", "VI"));
attacks.Add("Hold Hands", new BaseAttack("Hold Hands", "Normal", "Status", "Cute", "40", "", "", "VI"));
attacks.Add("Baby-Doll Eyes", new BaseAttack("Baby-Doll Eyes", "Fairy", "Status", "Cute", "30", "", "100", "VI"));
attacks.Add("Nuzzle", new BaseAttack("Nuzzle", "Electric", "Physical", "Cute", "20", "20", "100", "VI"));
attacks.Add("Hold Back", new BaseAttack("Hold Back", "Normal", "Physical", "Cool", "40", "40", "100", "VI"));
attacks.Add("Infestation", new BaseAttack("Infestation", "Bug", "Special", "Cute", "20", "20", "100", "VI"));
attacks.Add("Power-Up Punch", new BaseAttack("Power-Up Punch", "Fighting", "Physical", "Tough", "20", "40", "100", "VI"));
attacks.Add("Oblivion Wing", new BaseAttack("Oblivion Wing", "Flying", "Special", "Cool", "10", "80", "100", "VI"));
attacks.Add("Thousand Arrows", new BaseAttack("Thousand Arrows", "Ground", "Physical", "Beautiful", "10", "90", "100", "VI"));
attacks.Add("Thousand Waves", new BaseAttack("Thousand Waves", "Ground", "Physical", "Tough", "10", "90", "100", "VI"));
attacks.Add("Land's Wrath", new BaseAttack("Land's Wrath", "Ground", "Physical", "Beautiful", "10", "90", "100", "VI"));
attacks.Add("Light of Ruin", new BaseAttack("Light of Ruin", "Fairy", "Special", "Beautiful", "5", "140", "90", "VI"));
attacks.Add("Origin Pulse", new BaseAttack("Origin Pulse", "Water", "Special", "Beautiful", "10", "110", "85", "VI"));
attacks.Add("Precipice Blades", new BaseAttack("Precipice Blades", "Ground", "Physical", "Cool", "10", "120", "85", "VI"));
attacks.Add("Dragon Ascent", new BaseAttack("Dragon Ascent", "Flying", "Physical", "Beautiful", "5", "120", "100", "VI"));
attacks.Add("Hyperspace Fury", new BaseAttack("Hyperspace Fury", "Dark", "Physical", "Tough", "5", "100", "", "VI"));
attacks.Add("Breakneck Blitz", new BaseAttack("Breakneck Blitz", "Normal", "Physical", "???", "1", "", "", "VII"));
// attacks.Add("Breakneck Blitz", new BaseAttack("Breakneck Blitz", "Normal", "Special", "???", "1", "", "", "VII"));
attacks.Add("All-Out Pummeling", new BaseAttack("All-Out Pummeling", "Fighting", "Physical", "???", "1", "", "", "VII"));
// attacks.Add("All-Out Pummeling", new BaseAttack("All-Out Pummeling", "Fighting", "Special", "???", "1", "", "", "VII"));
// attacks.Add("Supersonic Skystrike", new BaseAttack("Supersonic Skystrike", "Flying", "Physical", "???", "1", "", "", "VII"));
attacks.Add("Supersonic Skystrike", new BaseAttack("Supersonic Skystrike", "Flying", "Special", "???", "1", "", "", "VII"));
attacks.Add("Acid Downpour", new BaseAttack("Acid Downpour", "Poison", "Physical", "???", "1", "", "", "VII"));
// attacks.Add("Acid Downpour", new BaseAttack("Acid Downpour", "Poison", "Special", "???", "1", "", "", "VII"));
// attacks.Add("Tectonic Rage", new BaseAttack("Tectonic Rage", "Ground", "Physical", "???", "1", "", "", "VII"));
attacks.Add("Tectonic Rage", new BaseAttack("Tectonic Rage", "Ground", "Special", "???", "1", "", "", "VII"));
attacks.Add("Continental Crush", new BaseAttack("Continental Crush", "Rock", "Physical", "???", "1", "", "", "VII"));
// attacks.Add("Continental Crush", new BaseAttack("Continental Crush", "Rock", "Special", "???", "1", "", "", "VII"));
// attacks.Add("Savage Spin-Out", new BaseAttack("Savage Spin-Out", "Bug", "Physical", "???", "1", "", "", "VII"));
attacks.Add("Savage Spin-Out", new BaseAttack("Savage Spin-Out", "Bug", "Special", "???", "1", "", "", "VII"));
attacks.Add("Never-Ending Nightmare", new BaseAttack("Never-Ending Nightmare", "Ghost", "Physical", "???", "1", "", "", "VII"));
// attacks.Add("Never-Ending Nightmare", new BaseAttack("Never-Ending Nightmare", "Ghost", "Special", "???", "1", "", "", "VII"));
// attacks.Add("Corkscrew Crash", new BaseAttack("Corkscrew Crash", "Steel", "Physical", "???", "1", "", "", "VII"));
attacks.Add("Corkscrew Crash", new BaseAttack("Corkscrew Crash", "Steel", "Special", "???", "1", "", "", "VII"));
attacks.Add("Inferno Overdrive", new BaseAttack("Inferno Overdrive", "Fire", "Physical", "???", "1", "", "", "VII"));
// attacks.Add("Inferno Overdrive", new BaseAttack("Inferno Overdrive", "Fire", "Special", "???", "1", "", "", "VII"));
// attacks.Add("Hydro Vortex", new BaseAttack("Hydro Vortex", "Water", "Physical", "???", "1", "", "", "VII"));
attacks.Add("Hydro Vortex", new BaseAttack("Hydro Vortex", "Water", "Special", "???", "1", "", "", "VII"));
attacks.Add("Bloom Doom", new BaseAttack("Bloom Doom", "Grass", "Physical", "???", "1", "", "", "VII"));
// attacks.Add("Bloom Doom", new BaseAttack("Bloom Doom", "Grass", "Special", "???", "1", "", "", "VII"));
// attacks.Add("Gigavolt Havoc", new BaseAttack("Gigavolt Havoc", "Electric", "Physical", "???", "1", "", "", "VII"));
attacks.Add("Gigavolt Havoc", new BaseAttack("Gigavolt Havoc", "Electric", "Special", "???", "1", "", "", "VII"));
attacks.Add("Shattered Psyche", new BaseAttack("Shattered Psyche", "Psychic", "Physical", "???", "1", "", "", "VII"));
// attacks.Add("Shattered Psyche", new BaseAttack("Shattered Psyche", "Psychic", "Special", "???", "1", "", "", "VII"));
// attacks.Add("Subzero Slammer", new BaseAttack("Subzero Slammer", "Ice", "Physical", "???", "1", "", "", "VII"));
attacks.Add("Subzero Slammer", new BaseAttack("Subzero Slammer", "Ice", "Special", "???", "1", "", "", "VII"));
attacks.Add("Devastating Drake", new BaseAttack("Devastating Drake", "Dragon", "Physical", "???", "1", "", "", "VII"));
// attacks.Add("Devastating Drake", new BaseAttack("Devastating Drake", "Dragon", "Special", "???", "1", "", "", "VII"));
// attacks.Add("Black Hole Eclipse", new BaseAttack("Black Hole Eclipse", "Dark", "Physical", "???", "1", "", "", "VII"));
attacks.Add("Black Hole Eclipse", new BaseAttack("Black Hole Eclipse", "Dark", "Special", "???", "1", "", "", "VII"));
attacks.Add("Twinkle Tackle", new BaseAttack("Twinkle Tackle", "Fairy", "Physical", "???", "1", "", "", "VII"));
// attacks.Add("Twinkle Tackle", new BaseAttack("Twinkle Tackle", "Fairy", "Special", "???", "1", "", "", "VII"));
attacks.Add("Catastropika", new BaseAttack("Catastropika", "Electric", "Physical", "???", "1", "210", "", "VII"));
attacks.Add("Shore Up", new BaseAttack("Shore Up", "Ground", "Status", "???", "10", "", "", "VII"));
attacks.Add("First Impression", new BaseAttack("First Impression", "Bug", "Physical", "???", "10", "90", "100", "VII"));
attacks.Add("Baneful Bunker", new BaseAttack("Baneful Bunker", "Poison", "Status", "???", "10", "", "", "VII"));
attacks.Add("Spirit Shackle", new BaseAttack("Spirit Shackle", "Ghost", "Physical", "???", "10", "80", "100", "VII"));
attacks.Add("Darkest Lariat", new BaseAttack("Darkest Lariat", "Dark", "Physical", "???", "10", "85", "100", "VII"));
attacks.Add("Sparkling Aria", new BaseAttack("Sparkling Aria", "Water", "Special", "???", "10", "90", "100", "VII"));
attacks.Add("Ice Hammer", new BaseAttack("Ice Hammer", "Ice", "Physical", "???", "10", "100", "90", "VII"));
attacks.Add("Floral Healing", new BaseAttack("Floral Healing", "Fairy", "Status", "???", "10", "", "", "VII"));
attacks.Add("High Horsepower", new BaseAttack("High Horsepower", "Ground", "Physical", "???", "10", "95", "95", "VII"));
attacks.Add("Strength Sap", new BaseAttack("Strength Sap", "Grass", "Status", "???", "10", "", "100", "VII"));
attacks.Add("Solar Blade", new BaseAttack("Solar Blade", "Grass", "Physical", "???", "10", "125", "100", "VII"));
attacks.Add("Leafage", new BaseAttack("Leafage", "Grass", "Physical", "???", "40", "40", "100", "VII"));
attacks.Add("Spotlight", new BaseAttack("Spotlight", "Normal", "Status", "???", "15", "", "", "VII"));
attacks.Add("Toxic Thread", new BaseAttack("Toxic Thread", "Poison", "Status", "???", "20", "", "100", "VII"));
attacks.Add("Laser Focus", new BaseAttack("Laser Focus", "Normal", "Status", "???", "30", "", "", "VII"));
attacks.Add("Gear Up", new BaseAttack("Gear Up", "Steel", "Status", "???", "20", "", "", "VII"));
attacks.Add("Throat Chop", new BaseAttack("Throat Chop", "Dark", "Physical", "???", "15", "80", "100", "VII"));
attacks.Add("Pollen Puff", new BaseAttack("Pollen Puff", "Bug", "Special", "???", "15", "90", "100", "VII"));
attacks.Add("Anchor Shot", new BaseAttack("Anchor Shot", "Steel", "Physical", "???", "20", "80", "100", "VII"));
attacks.Add("Psychic Terrain", new BaseAttack("Psychic Terrain", "Psychic", "Status", "???", "10", "", "", "VII"));
attacks.Add("Lunge", new BaseAttack("Lunge", "Bug", "Physical", "???", "15", "80", "100", "VII"));
attacks.Add("Fire Lash", new BaseAttack("Fire Lash", "Fire", "Physical", "???", "15", "80", "100", "VII"));
attacks.Add("Power Trip", new BaseAttack("Power Trip", "Dark", "Physical", "???", "10", "20", "100", "VII"));
attacks.Add("Burn Up", new BaseAttack("Burn Up", "Fire", "Special", "???", "5", "130", "100", "VII"));
attacks.Add("Speed Swap", new BaseAttack("Speed Swap", "Psychic", "Status", "???", "10", "", "", "VII"));
attacks.Add("Smart Strike", new BaseAttack("Smart Strike", "Steel", "Physical", "???", "10", "70", "", "VII"));
attacks.Add("Purify", new BaseAttack("Purify", "Poison", "Status", "???", "20", "", "", "VII"));
attacks.Add("Revelation Dance", new BaseAttack("Revelation Dance", "Normal", "Special", "???", "15", "90", "100", "VII"));
attacks.Add("Core Enforcer", new BaseAttack("Core Enforcer", "Dragon", "Special", "???", "10", "100", "100", "VII"));
attacks.Add("Trop Kick", new BaseAttack("Trop Kick", "Grass", "Physical", "???", "15", "70", "100", "VII"));
attacks.Add("Instruct", new BaseAttack("Instruct", "Psychic", "Status", "???", "15", "", "", "VII"));
attacks.Add("Beak Blast", new BaseAttack("Beak Blast", "Flying", "Physical", "???", "15", "100", "100", "VII"));
attacks.Add("Clanging Scales", new BaseAttack("Clanging Scales", "Dragon", "Special", "???", "5", "110", "100", "VII"));
attacks.Add("Dragon Hammer", new BaseAttack("Dragon Hammer", "Dragon", "Physical", "???", "15", "90", "100", "VII"));
attacks.Add("Brutal Swing", new BaseAttack("Brutal Swing", "Dark", "Physical", "???", "20", "60", "100", "VII"));
attacks.Add("Aurora Veil", new BaseAttack("Aurora Veil", "Ice", "Status", "???", "20", "", "", "VII"));
attacks.Add("Sinister Arrow Raid", new BaseAttack("Sinister Arrow Raid", "Ghost", "Physical", "???", "1", "180", "", "VII"));
attacks.Add("Malicious Moonsault", new BaseAttack("Malicious Moonsault", "Dark", "Physical", "???", "1", "180", "", "VII"));
attacks.Add("Oceanic Operetta", new BaseAttack("Oceanic Operetta", "Water", "Special", "???", "1", "195", "", "VII"));
attacks.Add("Guardian of Alola", new BaseAttack("Guardian of Alola", "Fairy", "Special", "???", "1", "", "", "VII"));
attacks.Add("Soul-Stealing 7-Star Strike", new BaseAttack("Soul-Stealing 7-Star Strike", "Ghost", "Physical", "???", "1", "195", "", "VII"));
attacks.Add("Stoked Sparksurfer", new BaseAttack("Stoked Sparksurfer", "Electric", "Special", "???", "1", "175", "", "VII"));
attacks.Add("Pulverizing Pancake", new BaseAttack("Pulverizing Pancake", "Normal", "Physical", "???", "1", "210", "", "VII"));
attacks.Add("Extreme Evoboost", new BaseAttack("Extreme Evoboost", "Normal", "Status", "???", "1", "", "", "VII"));
attacks.Add("Genesis Supernova", new BaseAttack("Genesis Supernova", "Psychic", "Special", "???", "1", "185", "", "VII"));
attacks.Add("Shell Trap", new BaseAttack("Shell Trap", "Fire", "Special", "???", "5", "150", "100", "VII"));
attacks.Add("Fleur Cannon", new BaseAttack("Fleur Cannon", "Fairy", "Special", "???", "5", "130", "90", "VII"));
attacks.Add("Psychic Fangs", new BaseAttack("Psychic Fangs", "Psychic", "Physical", "???", "10", "85", "100", "VII"));
attacks.Add("Stomping Tantrum", new BaseAttack("Stomping Tantrum", "Ground", "Physical", "???", "10", "75", "100", "VII"));
attacks.Add("Shadow Bone", new BaseAttack("Shadow Bone", "Ghost", "Physical", "???", "10", "85", "100", "VII"));
attacks.Add("Accelerock", new BaseAttack("Accelerock", "Rock", "Physical", "???", "20", "40", "100", "VII"));
attacks.Add("Liquidation", new BaseAttack("Liquidation", "Water", "Physical", "???", "10", "85", "100", "VII"));
attacks.Add("Prismatic Laser", new BaseAttack("Prismatic Laser", "Psychic", "Special", "???", "10", "160", "100", "VII"));
attacks.Add("Spectral Thief", new BaseAttack("Spectral Thief", "Ghost", "Physical", "???", "10", "90", "100", "VII"));
attacks.Add("Sunsteel Strike", new BaseAttack("Sunsteel Strike", "Steel", "Physical", "???", "5", "100", "100", "VII"));
attacks.Add("Moongeist Beam", new BaseAttack("Moongeist Beam", "Ghost", "Special", "???", "5", "100", "100", "VII"));
attacks.Add("Tearful Look", new BaseAttack("Tearful Look", "Normal", "Status", "???", "20", "", "", "VII"));
attacks.Add("Zing Zap", new BaseAttack("Zing Zap", "Electric", "Physical", "???", "10", "80", "100", "VII"));
attacks.Add("Nature's Madness", new BaseAttack("Nature's Madness", "Fairy", "Special", "???", "10", "", "90", "VII"));
attacks.Add("Multi-Attack", new BaseAttack("Multi-Attack", "Normal", "Physical", "???", "10", "90", "100", "VII"));
attacks.Add("10,000,000 Volt Thunderbolt", new BaseAttack("10,000,000 Volt Thunderbolt", "Electric", "Special", "???", "1", "195", "", "VII"));


    }
}
}